### PR TITLE
sils/style

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by sils** [comment]
@Cretezy ping?

**Comment by sils** [comment]
@Cretezy do you need help maintaining this package? Eventually we'll have no choice but do an own fork if nothing happens here as well :/ pymessenger3 (without python 2 support :smiling_imp: )

**Comment by Cretezy** [comment]
Going to look over all of this tomorrow. Sorry about the delay, so far looks good!

**Comment by sils** [comment]
thanks a lot :)

**Comment by Cretezy** [comment]
Looks good overall. I'm going to merge right after you bump version up to 3.0.0 (because we have breaking changes). :+1:

**Comment by sils** [comment]
Bumped version, I guess the new download URL will work when you do a release on GitHub?

**Comment by Cretezy** [comment]
Yep!

**Comment by Cretezy** [comment]
Since you made all the changes to this release, can you draft a release description? (changelog)

**Comment by sils** [comment]
@Cretezy not sure what kind of style you prefer, couldn't find any existing changelog. I just added loads of new elements (esp. Airline templates and Buttons) plus some internal changes (esp. auto jsonifying attrs classes), I'm not even sure if (where?) I'm breaking the public API.

**Comment by Cretezy** [comment]
https://github.com/Cretezy/pymessenger2/releases/tag/v3.0.0

**Pull request merged**
