### PR TITLE
Added Quick Reply Support!

### PR DESCRIPTION
**Pull request by ghost**
Added new button class for quick reply.
Fixed unicode error for Python3 under _utils.py_

Usage can be found on test

### CODE REVIEW

**Comment by madEng84** [comment]
Why don't you merge this? @Cretezy 
Travis?

This feature is very useful

**Comment by Cretezy** [comment]
Merged!

**Comment by Cretezy** [comment]
Pushed with v3.1.0.

**Comment by madEng84** [comment]
Great!

**Pull request merged**
